# source: https://onlinelibrary.wiley.com/doi/10.1111/1475-679X.12575 (Global Evolution of Environmental and Social Disclosure in Annual Reports - Lin et al.)

csrd_seeds = [
    "carbon footprint",
    "co2 emission",
    "climate change",
    "GHG emission",
    "global warming",
    "greenhouse gas",
    "Scope 1",
    "Scope 2",
    "Scope 3",
    "electricity consumption",
    "fossil fuel",
    "heating consumption",
    "steam consumption",
    "water consumption",
    "gas consumption",
    "air pollution",
    "air quality",
    "particulate matter",
    "pollution",
    "hazardous waste",
    "noise pollution",
    "landfill",
    "waste water",
    "waste",
    "biodiversity",
    "deforestation",
    "natural habitat",
    "reforestation",
    "fauna and flora",
    "ecosystem",
    "career development",
    "diversity and inclusion",
    "employee engagement",
    "gender diversity",
    "health and safety",
    "human capital",
    "human right",
    "forced labor",
    "slavery",
    "consumer privacy",
    "customer privacy",
    "customer welfare",
    "data protection",
    "responsible marketing",
    "product quality",
    "supply chain sustainability",
    "community relation",
    "local community",
    "social capital",
    "community engagement",
    "corruption",
    "bribery",
]

csrd_words = [
    "emission",
    "climate",
    "climate change",
    "greenhouse gas",
    "co2 emission",
    "carbon",
    "co2",
    "carbon footprint",
    "carbon emission",
    "GHG emission",
    "SDG",
    "carbon dioxide",
    "warming",
    "sustainability performance",
    "emission reduction",
    "co2e",
    "emission factor",
    "energy transition",
    "tco2e",
    "scope 1",
    "gas",
    "oil",
    "water",
    "consumption",
    "electricity",
    "fuel",
    "coal",
    "energy consumption",
    "production volume",
    "wood",
    "water consumption",
    "kwh",
    "energy saving",
    "diesel",
    "energy source",
    "heating",
    "steam",
    "fuel consumption",
    "electricity consumption",
    "mwh",
    "waste",
    "transport",
    "chemical",
    "packaging",
    "plastic",
    "recycling",
    "energy efficiency",
    "hazardous",
    "pollution",
    "soil",
    "waste management",
    "reuse",
    "hazard",
    "effluent",
    "water treatment",
    "water supply",
    "landfill",
    "noise",
    "waste water",
    "harmful",
    "conservation",
    "urban",
    "landscape",
    "ecosystem",
    "ecological",
    "forest",
    "biodiversity",
    "specie",
    "palm oil",
    "heritage",
    "planet",
    "planting",
    "river",
    "water resource",
    "habitat",
    "ocean",
    "wild",
    "flora",
    "fauna",
    "animal welfare",
    "ethical",
    "workforce",
    "talent",
    "workplace",
    "ethic",
    "gender",
    "colleague",
    "discrimination",
    "work environment",
    "nurture",
    "employee engagement",
    "gender diversity",
    "motivation",
    "career development",
    "equality",
    "working environment",
    "diversity policy",
    "business ethic",
    "performance management",
    "board diversity",
    "technological",
    "reliability",
    "reputation",
    "productivity",
    "product development",
    "supply chain",
    "customer service",
    "competitiveness",
    "customer satisfaction",
    "stringent",
    "product range",
    "legislative",
    "information system",
    "production process",
    "ingredient",
    "functionality",
    "quality control",
    "customer experience",
    "confidentiality",
    "quality product",
    "corruption",
    "citizen",
    "violation",
    "business partner",
    "offense",
    "cultural",
    "educational",
    "misconduct",
    "harassment",
    "bribery",
    "criminal",
    "illegal",
    "welfare",
    "unethical",
    "socially",
    "well-being",
    "well-being",
    "indigenous",
    "youth",
    "stakeholder engagement",
]
